import communication_networks_operations_research_networks_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace communication_networks_operations_research_networks_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end communication_networks_operations_research_networks_lemma_canonical_lane_mathlib
end HautevilleHouse
